name: 01b Hola mundo
on:
  push:  # Se lanza el workflow al hacer un push  
jobs:
  # This workflow contains a single job called "hola-mundo"
  hola-Yoli:   # Nombre del job
    runs-on: ubuntu-latest      # The type of runner that the job will run on
    steps:
    - name: Autosaludo
      run: echo "Â¡Hola, Yoli!"