name: 03b - build node application
on:
  push: #se dispara al hacer push sobre la rama main
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # hacer checkout del c칩digo
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4   # coordenadas = owner del repo / repo @ versi칩n
        with:  # inputs de par치metros
          node-version: 20
      - run: npm ci  # construcci칩n
      - run: npm test   # lanzar pruebas